ARTE-TECH/src/Entity/Timesheet.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TimesheetsRepository")
 * @ApiResource(iri="http://schema.org/Offer")
 */
class Timesheet implements \ArrayAccess
{

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="timesheets")
     */

    // private $employee;

    // public function getEmployee(): ?Employee
    // {
    //     return $this->employee_id;
    // }

    // public function setEmployee(?Employee $employee): self
    // {
    //     $this->employee_id = $employee;

    //     return $this;
    // }

    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $employee_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $rate_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $customer_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $pauze;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activities;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $materials;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hourly_rate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $transport_cost;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_accepted;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmployeeId(): ?int
    {
        return $this->employee_id;
    }

    public function setEmployeeId(int $employee_id): self
    {
        $this->employee_id = $employee_id;

        return $this;
    }

    public function getRateId(): ?int
    {
        return $this->rate_id;
    }

    public function setRateId(int $rate_id): self
    {
        $this->rate_id = $rate_id;

        return $this;
    }

    public function getCustomerId(): ?int
    {
        return $this->customer_id;
    }

    public function setCustomerId(int $customer_id): self
    {
        $this->customer_id = $customer_id;

        return $this;
    }

    public function getStartDate()
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getPauze(): ?int
    {
        return $this->pauze;
    }

    public function setPauze(int $pauze): self
    {
        $this->pauze = $pauze;

        return $this;
    }

    public function getActivities(): ?string
    {
        return $this->activities;
    }

    public function setActivities(string $activities): self
    {
        $this->activities = $activities;

        return $this;
    }

    public function getMaterials(): ?string
    {
        return $this->materials;
    }

    public function setMaterials(?string $materials): self
    {
        $this->materials = $materials;

        return $this;
    }

    public function getHourlyRate(): ?int
    {
        return $this->hourly_rate;
    }

    public function setHourlyRate(?int $hourly_rate): self
    {
        $this->hourly_rate = $hourly_rate;

        return $this;
    }

    public function getTransportCost(): ?int
    {
        return $this->transport_cost;
    }

    public function setTransportCost(?int $transport_cost): self
    {
        $this->transport_cost = $transport_cost;

        return $this;
    }

    public function offsetExists($offset) {
        return isset($this->$offset);
    }

    public function offsetSet($offset, $value) {
        $this->$offset = $value;
    }

    public function offsetGet($offset) {
        return $this->$offset;
    }

    public function offsetUnset($offset) {
        $this->$offset = null;
    }

    public function getIsAccepted(): ?bool
    {
        return $this->is_accepted;
    }

    public function setIsAccepted(?bool $is_accepted): self
    {
        $this->is_accepted = $is_accepted;

        return $this;
    }
}

ARTE-TECH/src/Controller/ManagerController.php
<?php

namespace App\Controller;

use App\Entity\Timesheet;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ManagerController extends AbstractController
{
    /**
     * @Route("/manager", name="manager")
     */
    public function index()
    {
        $timesheets = $this->getDoctrine()
        ->getRepository(Timesheet::class)
        ->findAll();

        $employees = $this->getDoctrine()
        ->getRepository(User::class)
        ->findBy(['role' => 'ROLE_EMPLOYEE']);

        $customers = $this->getDoctrine()
        ->getRepository(User::class)
        ->findBy(['role' => 'ROLE_CUSTOMER']);

        return $this->render('manager/index.html.twig', [
            'controller_name' => 'ManagerController',
            'timesheets' => $timesheets,
            'employees' => $employees,
            'customers' => $customers,
        ]);
    }
   

}

ARTE-TECH/templates/manager/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ManagerController!{% endblock %}

{% block body %}

<h1>ARTE-TECH</h1>
    <h2>Timesheets</h2>
<div class="nav-container">
    <div class="navigation">
        <div class="nav-element"><a href="{{ path('manager') }}">Manager</a></div>
        <div class="nav-element"><a href="{{ path('customers') }}">Klanten</a></div>
        <div class="nav-element"><a href="{{ path('app_logout') }}">Uitloggen</a></div>
    </div>
</div>
{# 
<a href="{{ path('create_timesheet') }}">Add timesheet</a> #}
<table class="timesheets-table">
<tr>
    <th>Datum</th>
    <th>Uren</th>
    <th>Werknemer</th>
    <th>Klant</th>
    <th>Bevestiging</th>
    <th>Opties</th>
</tr>
{% for timesheet in timesheets %}
<tr>
    <td>{{ timesheet['start_date']|date('l d/m/y') }}</td>
    <td>{{ timesheet['end_date'].diff(timesheet['start_date'])|date('%hu%mm') }}</td>
    {% for employee in employees %}
        {% if employee.id == timesheet['employee_id'] %}
        <td>{{ employee.name }}</td>
        {% endif %}
    {% endfor %}
    {% for customer in customers %}
        {% if customer.id == timesheet['customer_id'] %}
        <td>{{ customer.name }}</td>
        {% endif %}
    {% endfor %}
    {% if timesheet.isAccepted == true %}
        <td>Geaccepteerd</td>
    {% else %}
    <td>Nog niet bevestigd</td>
    {% endif %}
    <td><a href="{{ path("edit_timesheet", {'id':timesheet.id}) }}">Bewerken</a><a href="{{ path("download_timesheet", {'id':timesheet.id}) }}">Downloaden</a></td>
</tr>
{% endfor %}
</table>
{# <ul>
{% for employee in employees %}
    <li>Employee: <a href="{{ path('view_employee', {'id':employee.id}) }}">{{ employee.name }}</a></li>
{% endfor %}
</ul> #}

{# {% for timesheet in timesheets %}
                <li>Customer is: {{ timesheet['customer_id'] }}</li>
                <li>Pauze: {{ timesheet.pauze }} minutes</li>
                <li>Time worked (Pauze excluded): {{ timesheet['end_date'].diff(timesheet['start_date'])|date('%h hours and %m minutes') }}</li>
                <li>Activities: {{ timesheet['activities'] }}</li>
                {% if timesheet.materials|default(null) %}
                <li>Materials: {{ timesheet['materials'] }}</li>
                {% endif %}
                {% if timesheet['hourly_rate']|default(null) %}
                <li>Hourly rate: {{ timesheet['hourly_rate'] }}</li>
                {% endif %}
                {% if timesheet['transport_cost']|default(null) %}
                <li>Transport cost: {{ timesheet['transport_cost'] }}</li>
                {% endif %}
                <li><a href="{{ path('edit_timesheet',  {'id': timesheet.id})}}">Edit</a></li>
{% endfor %} #}


{% endblock %}